#!/bin/sh
W=800
H=400

text="$(xsel -o)"
translate="$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=nl&dt=t&q=$(echo $text | sed "s/[\"'<>]//g")" | sed "s/,,,0]],,.*//g" | awk -F'"' '{print $2, $6}')"
#echo -e "Original text:" "$text"'\n' > /tmp/notitrans
echo "$translate" > /tmp/notitrans
zenity --text-info --title="Translation of selection" --filename=/tmp/notitrans --width=$W --height=$H --editable
